--Clear Rx Recoveries
DELETE FROM DL_EMP_TBL.RX_RECOVERIES;
--Load Rx Recoveries
insert into dl_emp_Tbl.rx_recoveries
select '1' as row_id,contract_num as client_cd,ma_num, cert_num, first_nm, last_nm, patient_dob_dt, SSN_NUM, group_cd, contract_num, carrier_cd, sum(remit_amt) as REMIT_AMT, sum(MA_PAID_AMT) as MA_PAID
from edw_ar_fl.artbase
where project_cd >= '31' 
and from_dos_dt >= add_months(current_date, -36)
and claim_type_cd = '12' 
and transact_status_cd = 'B'
and remit_amt > 1000 
group by 1,2,3,4,5,6,7,8,9,10,11
;
--Clear Med Recoveries
DELETE FROM DL_EMP_TBL.MED_RECOVERIES;
--Load Med Recoveries
INSERT INTO DL_EMP_TBL.MED_RECOVERIES
select '1' as ROW_ID, contract_num as CLIENT_CD,ma_num, cert_num, first_nm, last_nm, patient_dob_dt, SSN_NUM, group_cd, contract_num, carrier_cd, sum(remit_amt) as REMIT_AMT, sum(MA_PAID_AMT) as MA_PAID
from edw_ar_fl.artbase
where project_cd >= '31' 
and from_dos_dt >= add_months(current_date, -36)
and claim_type_cd not in ('11', '12')
and transact_status_cd in ('A','B')
--and remit_amt >0 
and ma_num in (select ma_num from DL_EMP_TBL.rx_recoveries)
group by 1,2,3,4,5,6,7,8,9,10,11
;
--Clear ELGF Recoveries 
DELETE FROM DL_EMP_TBL.ELGF_RECOVERIES;
--Load ELGF Recoveries Introduce Segment ID
INSERT INTO DL_EMP_TBL.ELGF_RECOVERIES
SELECT  '1' as ROW_ID, E.CLIENT_CD,E.RI_MA_NUM,E.DP_LAST_NM,E.PH_LAST_NM,E.DP_FIRST_NM,E.PH_FIRST_NM,E.DP_GENCD_RF,
		E.PH_GENCD_RF,E.PH_DOB_DT,E.DP_DOB_DT,E.PH_SSN_NUM,E.DP_SSN_NUM,E.CARRIER_CD,
		E.POLICY_NUM,'RX' AS COVERAGE_TYPE_CD,E.PH_ADDRESS1_TXT,E.PH_CITY_TXT,E.PH_STATE_CD,
		E.PH_ZIP_CD,E.CARRIER_OFFICE_CD,E.GROUP_NUM,E.ELGF_ID,E.RSHCD_RF,E.SEGMENT_ID
FROM Dl_EMP_TBL.RX_RECOVERIES as R LEFT JOIN EDW_ELG_FL.ARTELGF as E
ON E.CLIENT_CD = R.CLIENT_CD and R.MA_NUM = E.RI_MA_NUM
WHERE E.RI_MA_NUM is not null
;
--Clear NEDB Recoveries
DELETE FROM DL_EMP_TBL.NEDB_RECOVERIES;
--Load NEDB Recoveries Unique Join on SEGMENT ID Bring in EMPLOYER NM
INSERT INTO DL_EMP_TBL.NEDB_RECOVERIES
SELECT 	'1' AS ROW_ID,N.DEPENDENT_FIRST_NM,N.DEPENDENT_LAST_NM,N.DEPENDENT_BIRTH_DT,
N.DEPENDENT_SSN_NUM,N.INSURED_ZIP_CD,N.POLICY_NUM,E.SEGMENT_ID,N.PHAR_ELIG_START_DT,N.PHAR_ELIG_STOP_DT,N.EMPLOYER_NM
FROM DL_EMP_TBL.ELGF_RECOVERIES as E JOIN EDW_ELG_FL.NED_525_BASE as N
on E.SEGMENT_ID = N.SEGMENT_ID
;
--Clear EMP LEAD INFO
DELETE FROM DL_EMP_TBL.EMP_LEAD_INFO;
--Reduce EMP SOT and Load EMP LEAD INFO **Remapped Carrier Cd and Lead fields as they were flip flopped**
INSERT INTO DL_EMP_TBL.EMP_LEAD_INFO
SELECT DISTINCT	'1' as LEAD_ID, R.CLIENT_CD,R.MA_NUM,E.DP_LAST_NM,E.PH_LAST_NM,E.DP_FIRST_NM,E.PH_FIRST_NM,
E.DP_GENCD_RF,E.PH_GENCD_RF,E.PH_DOB_DT,E.DP_DOB_DT,E.PH_SSN_NUM,
--Med Carrier Code Inserted Here
EMP.MED_CARRIER_CD as CARRIER_CD,
--------------------------------
E.POLICY_NUM, 'MED' AS COVERAGE_TYPE_CD,N.ELIG_START_DT AS COVERAGE_START_DT,N.ELIG_STOP_DT AS COVERAGE_END_DT,
E.PH_ADDRESS1_TXT,E.PH_CITY_TXT,E.PH_STATE_CD,E.PH_ZIP_CD,E.CARRIER_OFFICE_CD,E.GROUP_NUM,E.ELGF_ID,E.RSHCD_RF,
E.DP_SSN_NUM as HDR_SSN_NUM, null as REJ_QA, 'Direct Bill Gaps Maxor,NavRx, etc.' as CMT_TXT,
'RX' AS LEAD_COVTP, N.EMPLOYER_NM AS LEAD_EMPLOYER,
EMP.RX_CARRIER_CD AS LEAD_CARRIER,EMP.RX_GROUP_NUM AS LEAD_GROUP_NUM,E.POLICY_NUM AS LEAD_POLICY_NUM
FROM DL_EMP_TBL.RX_RECOVERIES R LEFT JOIN DL_EMP_TBL.MED_RECOVERIES M
ON R.CLIENT_CD = M.CLIENT_CD and R.MA_NUM = M.MA_NUM
LEFT JOIN DL_EMP_TBL.ELGF_RECOVERIES E
ON R.CLIENT_CD = E.CLIENT_CD and R.MA_NUM = E.RI_MA_NUM
LEFT JOIN DL_EMP_TBL.NEDB_RECOVERIES N
ON E.SEGMENT_ID = N.SEGMENT_ID
LEFT JOIN (
SELECT RX_CARRIER_CD, RX_GROUP_NUM, MED_CARRIER_CD, TOTAL_CNT
FROM DL_EMP_TBL.EMP_SOT
QUALIFY ROW_NUMBER() OVER (PARTITION BY RX_CARRIER_CD, RX_GROUP_NUM ORDER BY TOTAL_CNT DESC) = 1
) EMP
ON R.GROUP_CD = EMP.RX_GROUP_NUM AND R.CARRIER_CD = EMP.RX_CARRIER_CD
WHERE M.MA_NUM is null and EMP.MED_CARRIER_CD is not null and
R.CARRIER_CD IN ('MAXOR', 'PTNRX', 'RXEDO', 'RXDMI', 
'BCMSR', 'CTRX', 'NAVRX', 'PRESO', 'SXC', 'APM',
'ARGUS','RXOPT', 'LDIRX','MEDIM', 'BCARD', 'USRPT')
;
--End
--Time: 00:03:14

