-- Microsoft SQL Server Management Studio 
-- Test Server: WTDBEIM001
-- Prod Server: WPDBEIM001

use [EIM_DB]
select config.DLFG_GROUP_ACTV_IND, config.DLFG_LOB, config.DLFG_GROUP_LOADPROCESS, CONFIG.DLGC_GROUPING_ID, CONFIG.DLFG_ENTERPRISE_PARTNER_NAME, CONFIG.DLFG_GROUP_NAME, CONFIG.DLFG_FILE_GROUP_COUNT, XWALK.DLFX_B2B_FILE_PROFILE_NAME, ig2.DLIC_B2B_FILE_PATTERN, CONFIG.DLFG_GROUP_CRE_USR,CONFIG.DLFG_SINGLE_FILE_CONSUMPTION_INDICATOR, CONFIG.DLFG_TWS_APP_NAME
from [dbo].[DL_FILE_GROUPING_CONFIG] CONFIG
left JOIN [dbo].[DL_EIM_GROUPING_FILE_XWALK] XWALK
ON CONFIG.DLGC_GROUPING_ID=XWALK.DLGC_GROUPING_ID
left join [dbo].[DL_INGEST_CONFIG_2] ig2
on xwalk.DLFX_B2B_FILE_PROFILE_NAME = ig2.DLIC_B2B_FILE_PROFILE_NAME
where CONFIG.[DLGC_GROUPING_ID]in ( '2672')
--XWALK.DLFX_B2B_FILE_PROFILE_NAME = 'INBD_VA_DMA_FHVAENRL_Client_Eligibility'
--config.dlfg_group_name like '%ark%'
--config.DLFG_TWS_APP_NAME like '%CLTDVATFLTSTG%'
group by config.DLFG_GROUP_ACTV_IND, config.DLFG_LOB, config.DLFG_GROUP_LOADPROCESS, CONFIG.DLGC_GROUPING_ID, CONFIG.DLFG_ENTERPRISE_PARTNER_NAME, CONFIG.DLFG_GROUP_NAME, CONFIG.DLFG_FILE_GROUP_COUNT, XWALK.DLFX_B2B_FILE_PROFILE_NAME, ig2.DLIC_B2B_FILE_PATTERN, CONFIG.DLFG_GROUP_CRE_USR,CONFIG.DLFG_SINGLE_FILE_CONSUMPTION_INDICATOR, CONFIG.DLFG_TWS_APP_NAME
