-- Microsoft SQL Server Management Studio 
-- Server: wpdbb2b003

use [B2BClientFileMetaData]
select *
from(
SELECT 
cast(INBDMD.EVENT_ID as int ) as EVENT_ID,
INBDMD.PARTNER_NM as B2B_PARTNER_NAME,
INBDMD.PROFILE_ID,
INBDMD.PROFILE_NAME,
INBDMD.ACCOUNT_NM,
INBDMD.ENTERPRISE_PARTNER_NAME as PARENT_PARTNER_NAME,
INBDMD.ENTERPRISE_PARTNER_ABBR as PARENT_PARTNER_ABBR,
INBDMD.ENTERPRISE_PARTNER_CODE as PARENT_PARTNER_CODE,
INBDMD.PARTNER_NAME as CHILD_PARTNER_NAME,
INBDMD.PARTNER_ABBR as CHILD_PARTNER_ABBR, 
INBDMD.PARTNER_CODE as CHILD_PARTNER_CODE,
INBDMD.INBD_FILE_PATH,
INBDMD.INBD_FILE_NM,
INBDMD.ORGINAL_FILE_NM,
INBDMD.FILE_DOMAIN,
INBDMD.FILE_CONTENT_TYPE,
INBDMD.FILE_COMPRESSION_TYPE,
INBDMD.FILE_REC_IN_DTM,
INBDMD.FILE_REC_OUT_DTM,
INBDMD.DEST_FILE_PATH,
INBDMD.DEST_FILE_NM,
INBDMD.FILE_STATUS,
INBDMD.INBD_LANDING_PATH,
INBDMD.FREQUENCY,
INBDMD.FILE_IND,
TRADING_PARTNER_TYPE,
ROW_NUMBER () OVER (PARTITION BY INBDMD.PROFILE_NAME ORDER BY INBDMD.FILE_REC_IN_DTM DESC) AS EVENT_ORDER
FROM DBO.SRC_INBD_METADATA AS INBDMD
where 1=1 AND 
--INBDMD.EVENT_ID = '1081187257'
--INBDMD.PROFILE_NAME in ('INBD_Benefit_Mgmt_Inc_MO_BMIELG_Carrier_Eligibility')
--INBDMD.DEST_FILE_NM like '%MDCD_MBR%'

) as A

where a.EVENT_ORDER ='1'
