-- Microsoft SQL Server Management Studio 
-- Test Server: WTDBEIM001
-- Prod Server: WPDBEIM001

Use EIM_DB;

;with cte1 AS (
select * from 
(select DLFG_GROUPING_ID, DLEFC_GROUPING_SEQ_NUMBER, DLEGC_GROUPING_STATUS, DLEGC_GROUPING_START_DT, DLEGC_GROUPING_END_DT, DLEFC_GROUPING_LAST_DT,
 DLEGC_GROUPING_CONSUMPTION_STATUS, DLEGC_GROUPING_FILE_COUNT_RECEIVED, DLEGC_GROUPING_FILE_JSON, DLEGC_GROUPING_FILE_COUNT_EXPECTED, DLEGC_GROUPING_MAX_FL_FREQ, 
ROW_NUMBER() OVER(PARTITION BY DLFG_GROUPING_ID ORDER BY DLEFC_GROUPING_SEQ_NUMBER DESC) AS ROW_NUM
from [dbo].[DL_EIM_GROUPING_CONTROL] 
where DLEGC_GROUPING_STATUS = 'DL_GROUP_COMPLETED' and DLEGC_GROUPING_CONSUMPTION_STATUS = 'CONSUMPTION_COMPLETED') tbl1
where ROW_NUM = 1),

tbl2 AS (Select DLFG_GROUPING_ID, DLEFC_GROUPING_SEQ_NUMBER, DLEGC_GROUPING_STATUS, DLEGC_GROUPING_START_DT, DLEGC_GROUPING_END_DT,DLEFC_GROUPING_LAST_DT,
DLEGC_GROUPING_CONSUMPTION_STATUS, DLEGC_GROUPING_FILE_COUNT_RECEIVED, DLEGC_GROUPING_FILE_COUNT_EXPECTED, DLEGC_GROUPING_MAX_FL_FREQ,
event_id, profile_name 
from cte1 
CROSS APPLY OPENJSON(DLEGC_GROUPING_FILE_JSON, '$.fileDetails')
WITH (event_id NVARCHAR(50) '$.eventIdB2B', profile_name NVARCHAR(100) '$.profileNameB2B'))

select GC.[DLFG_GROUP_CRE_USR], GC.[DLFG_REC_INSERT_TIME], GC.[DLFG_ENTERPRISE_PARTNER_NAME], GC.[DLFG_GROUP_NAME], 
       GC.[DLGC_GROUPING_ID], GC.[DLFG_GROUP_LOADPROCESS], GC.[DLFC_GROUP_FREQUENCY], GC.[DLFG_TWS_APP_NAME], 
	   GC.[DLFG_SINGLE_FILE_CONSUMPTION_INDICATOR], GC.[DLFG_FILE_GROUP_COUNT],GC.[DLFC_GROUP_DESCRIPTION],
	   TC.DLEFC_GROUPING_SEQ_NUMBER, TC.DLEGC_GROUPING_STATUS, TC.DLEGC_GROUPING_START_DT, TC.DLEGC_GROUPING_END_DT, TC.DLEFC_GROUPING_LAST_DT,
       TC.DLEGC_GROUPING_CONSUMPTION_STATUS, TC.DLEGC_GROUPING_FILE_COUNT_RECEIVED, TC.DLEGC_GROUPING_FILE_COUNT_EXPECTED,
	   TC.DLEGC_GROUPING_MAX_FL_FREQ,TC.event_id, TC.profile_name,
	   FC.[DLFC_FILE_NAME], FC.[DLFC_DLK_LZ_PATH], FC.[DLFC_PARTNER_NAME], FC.[DLFC_STATUS],
	   FC.[DLFC_START_DTM], FC.[DLFC_END_DTM], FC.[DLFC_CONFIG_ID], FC.[DLFC_LOB], FC.[DLFC_FREQUENCY],
	   IC.[DLIC_B2B_FILE_DOMAIN], IC.[DLIC_B2B_FILE_PATTERN], IC.[DLIC_DLK_FILE_DATA_TYPE]

FROM [dbo].[DL_FILE_GROUPING_CONFIG] GC,
     tbl2 TC,
     [dbo].[DL_FILE_CONTROL] FC,
     [dbo].[DL_INGEST_CONFIG_2] IC
WHERE GC.[DLGC_GROUPING_ID] = TC.DLFG_GROUPING_ID
AND   TC.event_id = FC.[DLFC_B2B_EVENT_ID]
AND   TC.profile_name = IC.DLIC_B2B_FILE_PROFILE_NAME
ORDER BY GC.[DLGC_GROUPING_ID]
    
